#this code is generated by ai. i wanted to learn about how NERF works by getting hands on experience, 
#and honestly this part just seemed a bit boring to me. this is a disclaimer that i have copy pasted 
#to every ai generated script in this repo

import torch
from mlp import mlp


def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    print("Using device:", device)

    # Model
    model = mlp().to(device)

    # Batch size
    batch_size = 1024

    # Positional encoding dimensions
    # Change these if your implementation uses different dimensions.
    position_dim = 60
    direction_dim = 16

    # Random encoded positions and viewing directions
    positions = torch.randn(
        batch_size,
        position_dim,
        device=device
    )

    directions = torch.randn(
        batch_size,
        direction_dim,
        device=device
    )

    # Forward pass
    sigma, rgb = model(positions, directions)

    print("\nForward pass successful!")

    print("Position shape:", positions.shape)
    print("Direction shape:", directions.shape)

    print("RGB shape:", rgb.shape)
    print("Sigma shape:", sigma.shape)

    print("\nRGB sample:", rgb[0])
    print("Sigma sample:", sigma[0])


if __name__ == "__main__":
    main()