#this code is generated by ai. i wanted to learn about how NERF works by getting hands on experience, 
#and honestly this part just seemed a bit boring to me. this is a disclaimer that i have copy pasted 
#to every ai generated script in this repo


import torch
import matplotlib

import matplotlib.pyplot as plt


from ray_generation import march_rays


BATCH_SIZE = 1024
IMAGE_RESOLUTION = 100
NEAR = 2.0
FAR = 6.0
N_SAMPLES = 64


# Mock sample image
# Uses the transform matrix from the Lego dataset example
sample_image = {
    "pose": torch.tensor([
        [
            -0.9999021887779236,
             0.004192245192825794,
            -0.013345719315111637,
            -0.05379832163453102
        ],
        [
            -0.013988681137561798,
            -0.2996590733528137,
             0.95394366979599,
             3.845470428466797
        ],
        [
            -4.656612873077393e-10,
             0.9540371894836426,
             0.29968830943107605,
             1.2080823183059692
        ],
        [
             0.0,
             0.0,
             0.0,
             1.0
        ]
    ], dtype=torch.float32)
}


# Run your ray generation + marching
points = march_rays(
    sample_image,
    camera_angle_x=0.69111,
    near_bound=NEAR,
    far_bound=FAR,
    samples=N_SAMPLES,
    batch_size=BATCH_SIZE
)


print("========== OUTPUT ==========")

print("Type:", type(points))
print("Number of sample steps:", len(points))

print("\nShape of each sample tensor:")

for i, sample in enumerate(points):
    print(f"Sample {i}: {sample.shape}")


print("\n========== EXPECTED ==========")

print("Number of rays:", BATCH_SIZE)
print("Number of samples:", N_SAMPLES)

print(
    "Expected shape of each sample:",
    f"[{BATCH_SIZE}, 3]"
)


print("\n========== CAMERA POSITION ==========")

camera_position = sample_image["pose"][:3, 3]

print("Camera position:")
print(camera_position)

print(
    "Distance from world origin:",
    torch.linalg.norm(camera_position).item()
)


print("\n========== SAMPLE DISTANCES ==========")

first_sample = points[0]
last_sample = points[-1]

distance_first = torch.linalg.norm(
    first_sample - camera_position,
    dim=1
)

distance_last = torch.linalg.norm(
    last_sample - camera_position,
    dim=1
)

print(
    "Distance of first samples from camera:"
)

print(
    "min:",
    distance_first.min().item()
)

print(
    "max:",
    distance_first.max().item()
)

print(
    "\nDistance of last samples from camera:"
)

print(
    "min:",
    distance_last.min().item()
)

print(
    "max:",
    distance_last.max().item()
)


print("\n========== VISUALIZATION ==========")

fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection="3d")


# Plot camera
ax.scatter(
    camera_position[0].item(),
    camera_position[1].item(),
    camera_position[2].item(),
    s=100,
    label="Camera"
)


# Plot a subset of rays
num_rays_to_plot = 50

for ray_index in range(num_rays_to_plot):

    ray_points = torch.stack([
        points[sample_index][ray_index]
        for sample_index in range(N_SAMPLES)
    ])

    ax.plot(
        ray_points[:, 0].numpy(),
        ray_points[:, 1].numpy(),
        ray_points[:, 2].numpy()
    )


ax.set_xlabel("X")
ax.set_ylabel("Y")
ax.set_zlabel("Z")

ax.set_title("NeRF Ray Generation + Ray Marching")

ax.legend()

plt.savefig("ray_marching.png")